server:
  port: 9001
spring:
  application:
    name: micro-aritcle
  datasource:
    url: jdbc:mysql://localhost:53306/dockerDB?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: lcw
    password: lcw2688499
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:57000/eureka
  instance:
    prefer-ip-address: true
